---
- hosts: freebsd

  tasks:
  - name: Check status of jailing
    shell: "sysctl security.jail.jailed | cut -d: -f2 | tr -d ' '"
    register: is_jail
    when: "ansible_os_family == 'FreeBSD'"

  - name: update freebsd
    command: " {{item }} "
    when: "ansible_os_family == 'FreeBSD' and is_jail.stdout == '0'"
    ignore_errors: yes
    with_items:
        - "freebsd-update --not-running-from-cron fetch"
        - "freebsd-update --not-running-from-cron  install"

  - name: update pkg
    command: " {{item }} "
    when: ansible_os_family == "FreeBSD"
    with_items:
        - "pkg update -q"
        - "pkg upgrade -y"
        - "pkg clean -qy"

  - name: Check for jails
    shell: "jls | grep -v JID | wc -l | tr -d ' '"
    register: has_jails
    when: "ansible_os_family == 'FreeBSD'"

  - name:  Update base jail
    command: 'ezjail-admin update -u'
    when: "ansible_os_family == 'FreeBSD' and has_jails.stdout != '0' and is_jail.stdout == '0'"
