---
- name: Generate configuration files
  template:
     src=asa_object.j2
     dest=/usr/local/share/ansible/cisco/output/firewalls/{{item.asa_hostname}}-asa_object-{{item.conf_type}}-{{ansible_date_time.iso8601}}.txt
  with_items: "{{asa_object_conf}}"
