---
- name: Generate configuration files
  template:
     src=any_os.j2
     dest=/usr/local/share/ansible/freeform/output/{{item.hostname}}-{{ansible_date_time.iso8601}}.txt
  with_items: "{{any_os}}"
