---
- name: Push Configuration to Network Device
  command: /usr/local/share/ansible/freeform/scripts/netmiko_push.py {{item.vendor}} {{item.hostname}} username password! output/{{item.hostname}}-{{ansible_date_time.iso8601}}.txt
  delegate_to: localhost
  with_items: "{{ any_os }}"
