---
- name: Push device configuration files
  hosts: localhost
  connection: local

  roles:
    - any_os

  tasks:
    - include: roles/freeform/tasks/push_napalm.yml
      when: (item.vendor == "junos") or
            (item.vendor == "eos") or
            (item.vendor == "nxos")
    - include: roles/freeform/tasks/push_netmiko.yml
      when: (item.vendor == "a10") or
            (item.vendor == "brocade") or
            (item.vendor == "cisco_ios") or
            (item.vendor == "cisco_ios_telnet")
